update get-transit-[j]ruby to work with rbenv

diff --git a/bin/get-transit-jruby b/bin/get-transit-jruby
--- a/bin/get-transit-jruby
+++ b/bin/get-transit-jruby
@@ -2,38 +2,18 @@
 
 cd `dirname $0`/../..
 
-# Load RVM into a shell session *as a function*
-if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
-
-  # First try to load from a user install
-  source "$HOME/.rvm/scripts/rvm"
-
-elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
-
-  # Then try to load from a root install
-  source "/usr/local/rvm/scripts/rvm"
-
-else
-
-  printf "ERROR: An RVM installation was not found.\n"
-  exit
-fi
-type rvm | head -1
+command -v rbenv >/dev/null 2>&1 || { echo >&2 "transit-ruby and transit-jruby require rbenv for testing. Aborting."; exit 1; }
 
 if [ ! -d "transit-jruby" ]; then
   git clone git@github.com:cognitect/transit-ruby.git transit-jruby
   cd transit-jruby
-  if [ -e "Gemfile.lock" ]; then
-    rm Gemfile.lock
-  fi
-
-  rvm --create jruby-1.7.13@verify-test
-  rvm gemset list
+  rbenv local jruby-1.7.13
   export JAVA_OPTS="-Xmx1g"
   ruby -S gem install bundler
   bundle install
   bundle exec rake compile
 else
+  cd transit-jruby
+  rbenv local jruby-1.7.13
   echo "transit-jruby exists"
 fi
-
